// ui/app/src/components/reload_prompt/ReloadPrompt.jsx
import React, { useEffect } from "react";
import { useAuthentication } from "@/providers/authentication/AuthenticationProvider";
import styles from "./styles.module.css";
import { useNotifications } from "@/providers/notifications/NotificationsProvider.jsx";

const ReloadPrompt = () => {
  const { needRefresh, acceptRefresh, showNotification } = useNotifications();
  const { user } = useAuthentication();
  const showUpdateNotes = user && user.getNews().length > 0;

  useEffect(() => {
    if (needRefresh && !showUpdateNotes) {
      acceptRefresh();
    }
  }, [needRefresh, showUpdateNotes]);

  return (
    <div className={styles.Container}>
      <div className={styles.Toast2}>
        <button className={styles.ToastButton} onClick={showNotification}>
          txomins
        </button>
      </div>
      {needRefresh && showUpdateNotes && (
        <div className={styles.Toast}>
          <div className={styles.Message}>
            <span>{getUser().getNews()}</span>
          </div>
          <button className={styles.ToastButton} onClick={acceptRefresh}>
            Reload
          </button>
          <button className={styles.ToastButton} onClick={close}>
            Close
          </button>
        </div>
      )}
    </div>
  );
};

export default ReloadPrompt;

// ui/app/src/lib/components/reload_prompt/ReloadPrompt.svelte
<script>
  import {auth} from "$lib/stores/auth";
  import {acceptRefresh, close, needRefresh, showNotification,} from "$lib/stores/notifications";

  const showUpdateNotes = $derived(
        () => $auth?.user && $auth.user.getNews().length > 0,
    );

    $effect(() => {
        if ($needRefresh && !showUpdateNotes) {
            acceptRefresh();
        }
    });
</script>

<div class="Container">
    <div class="Toast2">
        <button class="ToastButton" onclick={showNotification}>
            txomins
        </button>
    </div>

    {#if $needRefresh && showUpdateNotes}
        <div class="Toast">
            <div class="ToastMessage">
                <span>{$auth.user.getNews()}</span>
            </div>
            <button class="ToastButton" onclick={acceptRefresh}>Reload</button>
            <button class="ToastButton" onclick={close}>Close</button>
        </div>
    {/if}
</div>

<style>
    .Container {
        padding: 0;
        margin: 0;
        width: 0;
        height: 0;
    }

    .Toast {
        position: fixed;
        right: 0;
        bottom: 0;
        margin: 16px;
        padding: 12px;
        border: 1px solid #8885;
        border-radius: 4px;
        z-index: 1;
        text-align: left;
        box-shadow: 3px 4px 5px 0 #8885;
        background-color: white;
    }

    .Toast2 {
        position: fixed;
        right: 0;
        top: 0;
        margin: 16px;
        padding: 12px;
        border: 1px solid #8885;
        border-radius: 4px;
        z-index: 1;
        text-align: left;
        box-shadow: 3px 4px 5px 0 #8885;
        background-color: white;
    }

    .ToastMessage {
        margin-bottom: 8px;
    }

    .ToastButton {
        border: 1px solid #8885;
        outline: none;
        margin-right: 5px;
        border-radius: 2px;
        padding: 3px 10px;
    }
</style>
