// ui/library/src/components/atoms/button/CoreButton.jsx
import { Button } from "@headlessui/react";
import "./styles.css";

export const BUTTON_TYPES = {
  DEFAULT: "",
  PRIMARY: "primary",
  SECONDARY: "secondary",
  TERTIARY: "tertiary",
  ERROR: "error",
};

const CoreButton = (props) => {
  const disabledStyle = () => (props.disabled ? "disabled" : "");
  const typeStyle = () => props.type ?? BUTTON_TYPES.DEFAULT;

  const clickEvent = (e) => {
    if (!props.disabled) {
      props.onClick(e);
    }
  };

  return (
    <Button
      className={`button ${typeStyle()} ${disabledStyle()}`}
      onClick={clickEvent}
      disabled={props.disabled}
    >
      {props.label}
    </Button>
  );
};

export default CoreButton;

// ui/library/src/components/atoms/button/CoreButton.svelte
<script>
  import "./styles.css";
  import { BUTTON_TYPES } from "./button.constants.js";

  export let label = "";
  export let type = BUTTON_TYPES.DEFAULT;
  export let disabled = false;
  export let onClick = () => {};

  const clickEvent = (event) => {
    if (!disabled) {
      onClick(event);
    }
  };

  $: disabledClass = disabled ? "disabled" : "";
  $: typeClass = type ?? BUTTON_TYPES.DEFAULT;
</script>

<button
  class={`button ${typeClass} ${disabledClass}`}
  on:click={clickEvent}
  disabled={disabled}
>
  {label}
</button>
